<?php
/**
 * PrepareTransactionsEVMsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  CryptoapisApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CryptoAPIs
 *
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace CryptoapisApiClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use CryptoapisApiClient\ApiException;
use CryptoapisApiClient\Configuration;
use CryptoapisApiClient\FormDataProcessor;
use CryptoapisApiClient\HeaderSelector;
use CryptoapisApiClient\ObjectSerializer;

/**
 * PrepareTransactionsEVMsApi Class Doc Comment
 *
 * @category Class
 * @package  CryptoapisApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PrepareTransactionsEVMsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'prepareAFungibleTokenTransferFromAddressEVM' => [
            'application/json',
        ],
        'prepareANonFungibleTokenTransferFromAddressEVM' => [
            'application/json',
        ],
        'prepareTransactionFromAddressEVM' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation prepareAFungibleTokenTransferFromAddressEVM
     *
     * Prepare A Fungible Token Transfer From Address EVM
     *
     * @param  string $blockchain Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc. (required)
     * @param  string $network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while networks like \&quot;testnet\&quot;, \&quot;mordor\&quot; are test networks. (required)
     * @param  string|null $context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user. (optional)
     * @param  \CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVMRB|null $prepareAFungibleTokenTransferFromAddressEVMRB prepareAFungibleTokenTransferFromAddressEVMRB (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['prepareAFungibleTokenTransferFromAddressEVM'] to see the possible values for this operation
     *
     * @throws \CryptoapisApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVMR|\CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVM400Response|\CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVM401Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs402Response|\CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVM403Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs409Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs415Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs422Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs429Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs500Response
     */
    public function prepareAFungibleTokenTransferFromAddressEVM($blockchain, $network, $context = null, $prepareAFungibleTokenTransferFromAddressEVMRB = null, string $contentType = self::contentTypes['prepareAFungibleTokenTransferFromAddressEVM'][0])
    {
        list($response) = $this->prepareAFungibleTokenTransferFromAddressEVMWithHttpInfo($blockchain, $network, $context, $prepareAFungibleTokenTransferFromAddressEVMRB, $contentType);
        return $response;
    }

    /**
     * Operation prepareAFungibleTokenTransferFromAddressEVMWithHttpInfo
     *
     * Prepare A Fungible Token Transfer From Address EVM
     *
     * @param  string $blockchain Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc. (required)
     * @param  string $network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while networks like \&quot;testnet\&quot;, \&quot;mordor\&quot; are test networks. (required)
     * @param  string|null $context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user. (optional)
     * @param  \CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVMRB|null $prepareAFungibleTokenTransferFromAddressEVMRB (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['prepareAFungibleTokenTransferFromAddressEVM'] to see the possible values for this operation
     *
     * @throws \CryptoapisApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVMR|\CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVM400Response|\CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVM401Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs402Response|\CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVM403Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs409Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs415Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs422Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs429Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs500Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function prepareAFungibleTokenTransferFromAddressEVMWithHttpInfo($blockchain, $network, $context = null, $prepareAFungibleTokenTransferFromAddressEVMRB = null, string $contentType = self::contentTypes['prepareAFungibleTokenTransferFromAddressEVM'][0])
    {
        $request = $this->prepareAFungibleTokenTransferFromAddressEVMRequest($blockchain, $network, $context, $prepareAFungibleTokenTransferFromAddressEVMRB, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVMR',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVM400Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVM401Response',
                        $request,
                        $response,
                    );
                case 402:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs402Response',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVM403Response',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs409Response',
                        $request,
                        $response,
                    );
                case 415:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs415Response',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs422Response',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs429Response',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs500Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVMR',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVMR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVM400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVM401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 402:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs402Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVM403Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs409Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 415:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs415Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs422Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs429Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs500Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation prepareAFungibleTokenTransferFromAddressEVMAsync
     *
     * Prepare A Fungible Token Transfer From Address EVM
     *
     * @param  string $blockchain Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc. (required)
     * @param  string $network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while networks like \&quot;testnet\&quot;, \&quot;mordor\&quot; are test networks. (required)
     * @param  string|null $context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user. (optional)
     * @param  \CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVMRB|null $prepareAFungibleTokenTransferFromAddressEVMRB (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['prepareAFungibleTokenTransferFromAddressEVM'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function prepareAFungibleTokenTransferFromAddressEVMAsync($blockchain, $network, $context = null, $prepareAFungibleTokenTransferFromAddressEVMRB = null, string $contentType = self::contentTypes['prepareAFungibleTokenTransferFromAddressEVM'][0])
    {
        return $this->prepareAFungibleTokenTransferFromAddressEVMAsyncWithHttpInfo($blockchain, $network, $context, $prepareAFungibleTokenTransferFromAddressEVMRB, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation prepareAFungibleTokenTransferFromAddressEVMAsyncWithHttpInfo
     *
     * Prepare A Fungible Token Transfer From Address EVM
     *
     * @param  string $blockchain Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc. (required)
     * @param  string $network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while networks like \&quot;testnet\&quot;, \&quot;mordor\&quot; are test networks. (required)
     * @param  string|null $context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user. (optional)
     * @param  \CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVMRB|null $prepareAFungibleTokenTransferFromAddressEVMRB (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['prepareAFungibleTokenTransferFromAddressEVM'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function prepareAFungibleTokenTransferFromAddressEVMAsyncWithHttpInfo($blockchain, $network, $context = null, $prepareAFungibleTokenTransferFromAddressEVMRB = null, string $contentType = self::contentTypes['prepareAFungibleTokenTransferFromAddressEVM'][0])
    {
        $returnType = '\CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVMR';
        $request = $this->prepareAFungibleTokenTransferFromAddressEVMRequest($blockchain, $network, $context, $prepareAFungibleTokenTransferFromAddressEVMRB, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'prepareAFungibleTokenTransferFromAddressEVM'
     *
     * @param  string $blockchain Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc. (required)
     * @param  string $network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while networks like \&quot;testnet\&quot;, \&quot;mordor\&quot; are test networks. (required)
     * @param  string|null $context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user. (optional)
     * @param  \CryptoapisApiClient\Model\PrepareAFungibleTokenTransferFromAddressEVMRB|null $prepareAFungibleTokenTransferFromAddressEVMRB (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['prepareAFungibleTokenTransferFromAddressEVM'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function prepareAFungibleTokenTransferFromAddressEVMRequest($blockchain, $network, $context = null, $prepareAFungibleTokenTransferFromAddressEVMRB = null, string $contentType = self::contentTypes['prepareAFungibleTokenTransferFromAddressEVM'][0])
    {

        // verify the required parameter 'blockchain' is set
        if ($blockchain === null || (is_array($blockchain) && count($blockchain) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $blockchain when calling prepareAFungibleTokenTransferFromAddressEVM'
            );
        }

        // verify the required parameter 'network' is set
        if ($network === null || (is_array($network) && count($network) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $network when calling prepareAFungibleTokenTransferFromAddressEVM'
            );
        }




        $resourcePath = '/prepare-transactions/evm/{blockchain}/{network}/fungible-tokens';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $context,
            'context', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($blockchain !== null) {
            $resourcePath = str_replace(
                '{' . 'blockchain' . '}',
                ObjectSerializer::toPathValue($blockchain),
                $resourcePath
            );
        }
        // path params
        if ($network !== null) {
            $resourcePath = str_replace(
                '{' . 'network' . '}',
                ObjectSerializer::toPathValue($network),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($prepareAFungibleTokenTransferFromAddressEVMRB)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($prepareAFungibleTokenTransferFromAddressEVMRB));
            } else {
                $httpBody = $prepareAFungibleTokenTransferFromAddressEVMRB;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation prepareANonFungibleTokenTransferFromAddressEVM
     *
     * Prepare A Non Fungible Token Transfer From Address EVM
     *
     * @param  string $blockchain Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc. (required)
     * @param  string $network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while networks like \&quot;testnet\&quot;, \&quot;mordor\&quot; are test networks. (required)
     * @param  string|null $context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user. (optional)
     * @param  \CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVMRB|null $prepareANonFungibleTokenTransferFromAddressEVMRB prepareANonFungibleTokenTransferFromAddressEVMRB (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['prepareANonFungibleTokenTransferFromAddressEVM'] to see the possible values for this operation
     *
     * @throws \CryptoapisApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVMR|\CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVM400Response|\CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVM401Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs402Response|\CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVM403Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs409Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs415Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs422Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs429Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs500Response
     */
    public function prepareANonFungibleTokenTransferFromAddressEVM($blockchain, $network, $context = null, $prepareANonFungibleTokenTransferFromAddressEVMRB = null, string $contentType = self::contentTypes['prepareANonFungibleTokenTransferFromAddressEVM'][0])
    {
        list($response) = $this->prepareANonFungibleTokenTransferFromAddressEVMWithHttpInfo($blockchain, $network, $context, $prepareANonFungibleTokenTransferFromAddressEVMRB, $contentType);
        return $response;
    }

    /**
     * Operation prepareANonFungibleTokenTransferFromAddressEVMWithHttpInfo
     *
     * Prepare A Non Fungible Token Transfer From Address EVM
     *
     * @param  string $blockchain Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc. (required)
     * @param  string $network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while networks like \&quot;testnet\&quot;, \&quot;mordor\&quot; are test networks. (required)
     * @param  string|null $context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user. (optional)
     * @param  \CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVMRB|null $prepareANonFungibleTokenTransferFromAddressEVMRB (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['prepareANonFungibleTokenTransferFromAddressEVM'] to see the possible values for this operation
     *
     * @throws \CryptoapisApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVMR|\CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVM400Response|\CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVM401Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs402Response|\CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVM403Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs409Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs415Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs422Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs429Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs500Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function prepareANonFungibleTokenTransferFromAddressEVMWithHttpInfo($blockchain, $network, $context = null, $prepareANonFungibleTokenTransferFromAddressEVMRB = null, string $contentType = self::contentTypes['prepareANonFungibleTokenTransferFromAddressEVM'][0])
    {
        $request = $this->prepareANonFungibleTokenTransferFromAddressEVMRequest($blockchain, $network, $context, $prepareANonFungibleTokenTransferFromAddressEVMRB, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVMR',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVM400Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVM401Response',
                        $request,
                        $response,
                    );
                case 402:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs402Response',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVM403Response',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs409Response',
                        $request,
                        $response,
                    );
                case 415:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs415Response',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs422Response',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs429Response',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs500Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVMR',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVMR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVM400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVM401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 402:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs402Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVM403Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs409Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 415:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs415Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs422Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs429Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs500Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation prepareANonFungibleTokenTransferFromAddressEVMAsync
     *
     * Prepare A Non Fungible Token Transfer From Address EVM
     *
     * @param  string $blockchain Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc. (required)
     * @param  string $network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while networks like \&quot;testnet\&quot;, \&quot;mordor\&quot; are test networks. (required)
     * @param  string|null $context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user. (optional)
     * @param  \CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVMRB|null $prepareANonFungibleTokenTransferFromAddressEVMRB (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['prepareANonFungibleTokenTransferFromAddressEVM'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function prepareANonFungibleTokenTransferFromAddressEVMAsync($blockchain, $network, $context = null, $prepareANonFungibleTokenTransferFromAddressEVMRB = null, string $contentType = self::contentTypes['prepareANonFungibleTokenTransferFromAddressEVM'][0])
    {
        return $this->prepareANonFungibleTokenTransferFromAddressEVMAsyncWithHttpInfo($blockchain, $network, $context, $prepareANonFungibleTokenTransferFromAddressEVMRB, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation prepareANonFungibleTokenTransferFromAddressEVMAsyncWithHttpInfo
     *
     * Prepare A Non Fungible Token Transfer From Address EVM
     *
     * @param  string $blockchain Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc. (required)
     * @param  string $network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while networks like \&quot;testnet\&quot;, \&quot;mordor\&quot; are test networks. (required)
     * @param  string|null $context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user. (optional)
     * @param  \CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVMRB|null $prepareANonFungibleTokenTransferFromAddressEVMRB (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['prepareANonFungibleTokenTransferFromAddressEVM'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function prepareANonFungibleTokenTransferFromAddressEVMAsyncWithHttpInfo($blockchain, $network, $context = null, $prepareANonFungibleTokenTransferFromAddressEVMRB = null, string $contentType = self::contentTypes['prepareANonFungibleTokenTransferFromAddressEVM'][0])
    {
        $returnType = '\CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVMR';
        $request = $this->prepareANonFungibleTokenTransferFromAddressEVMRequest($blockchain, $network, $context, $prepareANonFungibleTokenTransferFromAddressEVMRB, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'prepareANonFungibleTokenTransferFromAddressEVM'
     *
     * @param  string $blockchain Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc. (required)
     * @param  string $network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while networks like \&quot;testnet\&quot;, \&quot;mordor\&quot; are test networks. (required)
     * @param  string|null $context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user. (optional)
     * @param  \CryptoapisApiClient\Model\PrepareANonFungibleTokenTransferFromAddressEVMRB|null $prepareANonFungibleTokenTransferFromAddressEVMRB (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['prepareANonFungibleTokenTransferFromAddressEVM'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function prepareANonFungibleTokenTransferFromAddressEVMRequest($blockchain, $network, $context = null, $prepareANonFungibleTokenTransferFromAddressEVMRB = null, string $contentType = self::contentTypes['prepareANonFungibleTokenTransferFromAddressEVM'][0])
    {

        // verify the required parameter 'blockchain' is set
        if ($blockchain === null || (is_array($blockchain) && count($blockchain) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $blockchain when calling prepareANonFungibleTokenTransferFromAddressEVM'
            );
        }

        // verify the required parameter 'network' is set
        if ($network === null || (is_array($network) && count($network) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $network when calling prepareANonFungibleTokenTransferFromAddressEVM'
            );
        }




        $resourcePath = '/prepare-transactions/evm/{blockchain}/{network}/non-fungible-tokens';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $context,
            'context', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($blockchain !== null) {
            $resourcePath = str_replace(
                '{' . 'blockchain' . '}',
                ObjectSerializer::toPathValue($blockchain),
                $resourcePath
            );
        }
        // path params
        if ($network !== null) {
            $resourcePath = str_replace(
                '{' . 'network' . '}',
                ObjectSerializer::toPathValue($network),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($prepareANonFungibleTokenTransferFromAddressEVMRB)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($prepareANonFungibleTokenTransferFromAddressEVMRB));
            } else {
                $httpBody = $prepareANonFungibleTokenTransferFromAddressEVMRB;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation prepareTransactionFromAddressEVM
     *
     * Prepare Transaction From Address EVM
     *
     * @param  string $blockchain Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc. (required)
     * @param  string $network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while network like \&quot;testnet\&quot; is a test network. (required)
     * @param  string $type Enum representation of the transaction type (required)
     * @param  string|null $context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user. (optional)
     * @param  \CryptoapisApiClient\Model\PrepareTransactionFromAddressEVMRB|null $prepareTransactionFromAddressEVMRB prepareTransactionFromAddressEVMRB (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['prepareTransactionFromAddressEVM'] to see the possible values for this operation
     *
     * @throws \CryptoapisApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \CryptoapisApiClient\Model\PrepareTransactionFromAddressEVMR|\CryptoapisApiClient\Model\PrepareTransactionFromAddressEVM400Response|\CryptoapisApiClient\Model\PrepareTransactionFromAddressEVM401Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs402Response|\CryptoapisApiClient\Model\PrepareTransactionFromAddressEVM403Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs409Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs415Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs422Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs429Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs500Response
     */
    public function prepareTransactionFromAddressEVM($blockchain, $network, $type, $context = null, $prepareTransactionFromAddressEVMRB = null, string $contentType = self::contentTypes['prepareTransactionFromAddressEVM'][0])
    {
        list($response) = $this->prepareTransactionFromAddressEVMWithHttpInfo($blockchain, $network, $type, $context, $prepareTransactionFromAddressEVMRB, $contentType);
        return $response;
    }

    /**
     * Operation prepareTransactionFromAddressEVMWithHttpInfo
     *
     * Prepare Transaction From Address EVM
     *
     * @param  string $blockchain Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc. (required)
     * @param  string $network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while network like \&quot;testnet\&quot; is a test network. (required)
     * @param  string $type Enum representation of the transaction type (required)
     * @param  string|null $context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user. (optional)
     * @param  \CryptoapisApiClient\Model\PrepareTransactionFromAddressEVMRB|null $prepareTransactionFromAddressEVMRB (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['prepareTransactionFromAddressEVM'] to see the possible values for this operation
     *
     * @throws \CryptoapisApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \CryptoapisApiClient\Model\PrepareTransactionFromAddressEVMR|\CryptoapisApiClient\Model\PrepareTransactionFromAddressEVM400Response|\CryptoapisApiClient\Model\PrepareTransactionFromAddressEVM401Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs402Response|\CryptoapisApiClient\Model\PrepareTransactionFromAddressEVM403Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs409Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs415Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs422Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs429Response|\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs500Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function prepareTransactionFromAddressEVMWithHttpInfo($blockchain, $network, $type, $context = null, $prepareTransactionFromAddressEVMRB = null, string $contentType = self::contentTypes['prepareTransactionFromAddressEVM'][0])
    {
        $request = $this->prepareTransactionFromAddressEVMRequest($blockchain, $network, $type, $context, $prepareTransactionFromAddressEVMRB, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\PrepareTransactionFromAddressEVMR',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\PrepareTransactionFromAddressEVM400Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\PrepareTransactionFromAddressEVM401Response',
                        $request,
                        $response,
                    );
                case 402:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs402Response',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\PrepareTransactionFromAddressEVM403Response',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs409Response',
                        $request,
                        $response,
                    );
                case 415:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs415Response',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs422Response',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs429Response',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs500Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\CryptoapisApiClient\Model\PrepareTransactionFromAddressEVMR',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\PrepareTransactionFromAddressEVMR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\PrepareTransactionFromAddressEVM400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\PrepareTransactionFromAddressEVM401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 402:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs402Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\PrepareTransactionFromAddressEVM403Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs409Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 415:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs415Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs422Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs429Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CryptoapisApiClient\Model\GetBlockDetailsByBlockHashUTXOs500Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation prepareTransactionFromAddressEVMAsync
     *
     * Prepare Transaction From Address EVM
     *
     * @param  string $blockchain Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc. (required)
     * @param  string $network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while network like \&quot;testnet\&quot; is a test network. (required)
     * @param  string $type Enum representation of the transaction type (required)
     * @param  string|null $context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user. (optional)
     * @param  \CryptoapisApiClient\Model\PrepareTransactionFromAddressEVMRB|null $prepareTransactionFromAddressEVMRB (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['prepareTransactionFromAddressEVM'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function prepareTransactionFromAddressEVMAsync($blockchain, $network, $type, $context = null, $prepareTransactionFromAddressEVMRB = null, string $contentType = self::contentTypes['prepareTransactionFromAddressEVM'][0])
    {
        return $this->prepareTransactionFromAddressEVMAsyncWithHttpInfo($blockchain, $network, $type, $context, $prepareTransactionFromAddressEVMRB, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation prepareTransactionFromAddressEVMAsyncWithHttpInfo
     *
     * Prepare Transaction From Address EVM
     *
     * @param  string $blockchain Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc. (required)
     * @param  string $network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while network like \&quot;testnet\&quot; is a test network. (required)
     * @param  string $type Enum representation of the transaction type (required)
     * @param  string|null $context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user. (optional)
     * @param  \CryptoapisApiClient\Model\PrepareTransactionFromAddressEVMRB|null $prepareTransactionFromAddressEVMRB (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['prepareTransactionFromAddressEVM'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function prepareTransactionFromAddressEVMAsyncWithHttpInfo($blockchain, $network, $type, $context = null, $prepareTransactionFromAddressEVMRB = null, string $contentType = self::contentTypes['prepareTransactionFromAddressEVM'][0])
    {
        $returnType = '\CryptoapisApiClient\Model\PrepareTransactionFromAddressEVMR';
        $request = $this->prepareTransactionFromAddressEVMRequest($blockchain, $network, $type, $context, $prepareTransactionFromAddressEVMRB, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'prepareTransactionFromAddressEVM'
     *
     * @param  string $blockchain Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc. (required)
     * @param  string $network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while network like \&quot;testnet\&quot; is a test network. (required)
     * @param  string $type Enum representation of the transaction type (required)
     * @param  string|null $context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user. (optional)
     * @param  \CryptoapisApiClient\Model\PrepareTransactionFromAddressEVMRB|null $prepareTransactionFromAddressEVMRB (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['prepareTransactionFromAddressEVM'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function prepareTransactionFromAddressEVMRequest($blockchain, $network, $type, $context = null, $prepareTransactionFromAddressEVMRB = null, string $contentType = self::contentTypes['prepareTransactionFromAddressEVM'][0])
    {

        // verify the required parameter 'blockchain' is set
        if ($blockchain === null || (is_array($blockchain) && count($blockchain) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $blockchain when calling prepareTransactionFromAddressEVM'
            );
        }

        // verify the required parameter 'network' is set
        if ($network === null || (is_array($network) && count($network) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $network when calling prepareTransactionFromAddressEVM'
            );
        }

        // verify the required parameter 'type' is set
        if ($type === null || (is_array($type) && count($type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $type when calling prepareTransactionFromAddressEVM'
            );
        }




        $resourcePath = '/prepare-transactions/evm/{blockchain}/{network}/native-coins';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $context,
            'context', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($blockchain !== null) {
            $resourcePath = str_replace(
                '{' . 'blockchain' . '}',
                ObjectSerializer::toPathValue($blockchain),
                $resourcePath
            );
        }
        // path params
        if ($network !== null) {
            $resourcePath = str_replace(
                '{' . 'network' . '}',
                ObjectSerializer::toPathValue($network),
                $resourcePath
            );
        }
        // path params
        if ($type !== null) {
            $resourcePath = str_replace(
                '{' . 'type' . '}',
                ObjectSerializer::toPathValue($type),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($prepareTransactionFromAddressEVMRB)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($prepareTransactionFromAddressEVMRB));
            } else {
                $httpBody = $prepareTransactionFromAddressEVMRB;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
