additionalProperties:
  licenseName: "MIT"
  variableNamingConvention: "camelCase"
  modern: "true"
  packageName: "MitinSany/CryptoapisApiClient"
  invokerPackage: "MitinSany/CryptoapisApiClient"
  composerPackageName: "mitinsany/cryptoapi-client-php"
  srcBasePath: "src"