<?php
/**
 * GetTransactionDetailsByTransactionHashUTXOsRIBSZ
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MitinSany/CryptoapisApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CryptoAPIs
 *
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MitinSany/CryptoapisApiClient\Model;

use \ArrayAccess;
use \MitinSany/CryptoapisApiClient\ObjectSerializer;

/**
 * GetTransactionDetailsByTransactionHashUTXOsRIBSZ Class Doc Comment
 *
 * @category Class
 * @description Zcash
 * @package  MitinSany/CryptoapisApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetTransactionDetailsByTransactionHashUTXOsRIBSZ implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetTransactionDetailsByTransactionHashUTXOsRIBSZ';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'expiryHeight' => 'int',
        'overwintered' => 'bool',
        'valueBalance' => '\MitinSany/CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRIBSZValueBalance',
        'versionGroupId' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'expiryHeight' => null,
        'overwintered' => null,
        'valueBalance' => null,
        'versionGroupId' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'expiryHeight' => false,
        'overwintered' => false,
        'valueBalance' => false,
        'versionGroupId' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'expiryHeight' => 'expiryHeight',
        'overwintered' => 'overwintered',
        'valueBalance' => 'valueBalance',
        'versionGroupId' => 'versionGroupId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'expiryHeight' => 'setExpiryHeight',
        'overwintered' => 'setOverwintered',
        'valueBalance' => 'setValueBalance',
        'versionGroupId' => 'setVersionGroupId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'expiryHeight' => 'getExpiryHeight',
        'overwintered' => 'getOverwintered',
        'valueBalance' => 'getValueBalance',
        'versionGroupId' => 'getVersionGroupId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('expiryHeight', $data ?? [], null);
        $this->setIfExists('overwintered', $data ?? [], null);
        $this->setIfExists('valueBalance', $data ?? [], null);
        $this->setIfExists('versionGroupId', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['expiryHeight'] === null) {
            $invalidProperties[] = "'expiryHeight' can't be null";
        }
        if ($this->container['overwintered'] === null) {
            $invalidProperties[] = "'overwintered' can't be null";
        }
        if ($this->container['valueBalance'] === null) {
            $invalidProperties[] = "'valueBalance' can't be null";
        }
        if ($this->container['versionGroupId'] === null) {
            $invalidProperties[] = "'versionGroupId' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets expiryHeight
     *
     * @return int
     */
    public function getExpiryHeight()
    {
        return $this->container['expiryHeight'];
    }

    /**
     * Sets expiryHeight
     *
     * @param int $expiryHeight Numeric representation of the transaction block height expiration
     *
     * @return self
     */
    public function setExpiryHeight($expiryHeight)
    {
        if (is_null($expiryHeight)) {
            throw new \InvalidArgumentException('non-nullable expiryHeight cannot be null');
        }
        $this->container['expiryHeight'] = $expiryHeight;

        return $this;
    }

    /**
     * Gets overwintered
     *
     * @return bool
     */
    public function getOverwintered()
    {
        return $this->container['overwintered'];
    }

    /**
     * Sets overwintered
     *
     * @param bool $overwintered overwintered
     *
     * @return self
     */
    public function setOverwintered($overwintered)
    {
        if (is_null($overwintered)) {
            throw new \InvalidArgumentException('non-nullable overwintered cannot be null');
        }
        $this->container['overwintered'] = $overwintered;

        return $this;
    }

    /**
     * Gets valueBalance
     *
     * @return \MitinSany/CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRIBSZValueBalance
     */
    public function getValueBalance()
    {
        return $this->container['valueBalance'];
    }

    /**
     * Sets valueBalance
     *
     * @param \MitinSany/CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRIBSZValueBalance $valueBalance valueBalance
     *
     * @return self
     */
    public function setValueBalance($valueBalance)
    {
        if (is_null($valueBalance)) {
            throw new \InvalidArgumentException('non-nullable valueBalance cannot be null');
        }
        $this->container['valueBalance'] = $valueBalance;

        return $this;
    }

    /**
     * Gets versionGroupId
     *
     * @return string
     */
    public function getVersionGroupId()
    {
        return $this->container['versionGroupId'];
    }

    /**
     * Sets versionGroupId
     *
     * @param string $versionGroupId String representation of the transaction version group id
     *
     * @return self
     */
    public function setVersionGroupId($versionGroupId)
    {
        if (is_null($versionGroupId)) {
            throw new \InvalidArgumentException('non-nullable versionGroupId cannot be null');
        }
        $this->container['versionGroupId'] = $versionGroupId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


