<?php
/**
 * GetTransactionDetailsByTransactionHashSolanaRI
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  CryptoapisApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CryptoAPIs
 *
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace CryptoapisApiClient\Model;

use \ArrayAccess;
use \CryptoapisApiClient\ObjectSerializer;

/**
 * GetTransactionDetailsByTransactionHashSolanaRI Class Doc Comment
 *
 * @category Class
 * @package  CryptoapisApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetTransactionDetailsByTransactionHashSolanaRI implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetTransactionDetailsByTransactionHashSolanaRI';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'fee' => '\CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashSolanaRIFee',
        'nativeBalanceChanges' => '\CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashSolanaRINativeBalanceChangesInner[]',
        'nativeMovements' => '\CryptoapisApiClient\Model\ListTransactionsByAddressSolanaRINativeMovementsInner[]',
        'signature' => 'string',
        'signer' => 'string',
        'timestamp' => 'int',
        'tokenBalanceChanges' => '\CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashSolanaRITokenBalanceChangesInner[]',
        'tokenMovements' => '\CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashSolanaRITokenMovementsInner[]',
        'minedInBlock' => '\CryptoapisApiClient\Model\ListTransactionsByAddressSolanaRIMinedInBlock'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'fee' => null,
        'nativeBalanceChanges' => null,
        'nativeMovements' => null,
        'signature' => null,
        'signer' => null,
        'timestamp' => 'int64',
        'tokenBalanceChanges' => null,
        'tokenMovements' => null,
        'minedInBlock' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'fee' => false,
        'nativeBalanceChanges' => false,
        'nativeMovements' => false,
        'signature' => false,
        'signer' => false,
        'timestamp' => false,
        'tokenBalanceChanges' => false,
        'tokenMovements' => false,
        'minedInBlock' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'fee' => 'fee',
        'nativeBalanceChanges' => 'nativeBalanceChanges',
        'nativeMovements' => 'nativeMovements',
        'signature' => 'signature',
        'signer' => 'signer',
        'timestamp' => 'timestamp',
        'tokenBalanceChanges' => 'tokenBalanceChanges',
        'tokenMovements' => 'tokenMovements',
        'minedInBlock' => 'minedInBlock'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'fee' => 'setFee',
        'nativeBalanceChanges' => 'setNativeBalanceChanges',
        'nativeMovements' => 'setNativeMovements',
        'signature' => 'setSignature',
        'signer' => 'setSigner',
        'timestamp' => 'setTimestamp',
        'tokenBalanceChanges' => 'setTokenBalanceChanges',
        'tokenMovements' => 'setTokenMovements',
        'minedInBlock' => 'setMinedInBlock'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'fee' => 'getFee',
        'nativeBalanceChanges' => 'getNativeBalanceChanges',
        'nativeMovements' => 'getNativeMovements',
        'signature' => 'getSignature',
        'signer' => 'getSigner',
        'timestamp' => 'getTimestamp',
        'tokenBalanceChanges' => 'getTokenBalanceChanges',
        'tokenMovements' => 'getTokenMovements',
        'minedInBlock' => 'getMinedInBlock'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('fee', $data ?? [], null);
        $this->setIfExists('nativeBalanceChanges', $data ?? [], null);
        $this->setIfExists('nativeMovements', $data ?? [], null);
        $this->setIfExists('signature', $data ?? [], null);
        $this->setIfExists('signer', $data ?? [], null);
        $this->setIfExists('timestamp', $data ?? [], null);
        $this->setIfExists('tokenBalanceChanges', $data ?? [], null);
        $this->setIfExists('tokenMovements', $data ?? [], null);
        $this->setIfExists('minedInBlock', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['fee'] === null) {
            $invalidProperties[] = "'fee' can't be null";
        }
        if ($this->container['nativeBalanceChanges'] === null) {
            $invalidProperties[] = "'nativeBalanceChanges' can't be null";
        }
        if ($this->container['nativeMovements'] === null) {
            $invalidProperties[] = "'nativeMovements' can't be null";
        }
        if ($this->container['signature'] === null) {
            $invalidProperties[] = "'signature' can't be null";
        }
        if ($this->container['signer'] === null) {
            $invalidProperties[] = "'signer' can't be null";
        }
        if ($this->container['timestamp'] === null) {
            $invalidProperties[] = "'timestamp' can't be null";
        }
        if ($this->container['tokenBalanceChanges'] === null) {
            $invalidProperties[] = "'tokenBalanceChanges' can't be null";
        }
        if ($this->container['tokenMovements'] === null) {
            $invalidProperties[] = "'tokenMovements' can't be null";
        }
        if ($this->container['minedInBlock'] === null) {
            $invalidProperties[] = "'minedInBlock' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets fee
     *
     * @return \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashSolanaRIFee
     */
    public function getFee()
    {
        return $this->container['fee'];
    }

    /**
     * Sets fee
     *
     * @param \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashSolanaRIFee $fee fee
     *
     * @return self
     */
    public function setFee($fee)
    {
        if (is_null($fee)) {
            throw new \InvalidArgumentException('non-nullable fee cannot be null');
        }
        $this->container['fee'] = $fee;

        return $this;
    }

    /**
     * Gets nativeBalanceChanges
     *
     * @return \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashSolanaRINativeBalanceChangesInner[]
     */
    public function getNativeBalanceChanges()
    {
        return $this->container['nativeBalanceChanges'];
    }

    /**
     * Sets nativeBalanceChanges
     *
     * @param \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashSolanaRINativeBalanceChangesInner[] $nativeBalanceChanges Object Array representation of the transactions native (SOL) balance changes of each address
     *
     * @return self
     */
    public function setNativeBalanceChanges($nativeBalanceChanges)
    {
        if (is_null($nativeBalanceChanges)) {
            throw new \InvalidArgumentException('non-nullable nativeBalanceChanges cannot be null');
        }
        $this->container['nativeBalanceChanges'] = $nativeBalanceChanges;

        return $this;
    }

    /**
     * Gets nativeMovements
     *
     * @return \CryptoapisApiClient\Model\ListTransactionsByAddressSolanaRINativeMovementsInner[]
     */
    public function getNativeMovements()
    {
        return $this->container['nativeMovements'];
    }

    /**
     * Sets nativeMovements
     *
     * @param \CryptoapisApiClient\Model\ListTransactionsByAddressSolanaRINativeMovementsInner[] $nativeMovements Object Array representation of the transactions native movements
     *
     * @return self
     */
    public function setNativeMovements($nativeMovements)
    {
        if (is_null($nativeMovements)) {
            throw new \InvalidArgumentException('non-nullable nativeMovements cannot be null');
        }
        $this->container['nativeMovements'] = $nativeMovements;

        return $this;
    }

    /**
     * Gets signature
     *
     * @return string
     */
    public function getSignature()
    {
        return $this->container['signature'];
    }

    /**
     * Sets signature
     *
     * @param string $signature String representation of the transaction's signature
     *
     * @return self
     */
    public function setSignature($signature)
    {
        if (is_null($signature)) {
            throw new \InvalidArgumentException('non-nullable signature cannot be null');
        }
        $this->container['signature'] = $signature;

        return $this;
    }

    /**
     * Gets signer
     *
     * @return string
     */
    public function getSigner()
    {
        return $this->container['signer'];
    }

    /**
     * Sets signer
     *
     * @param string $signer String representation of the transaction's signer
     *
     * @return self
     */
    public function setSigner($signer)
    {
        if (is_null($signer)) {
            throw new \InvalidArgumentException('non-nullable signer cannot be null');
        }
        $this->container['signer'] = $signer;

        return $this;
    }

    /**
     * Gets timestamp
     *
     * @return int
     */
    public function getTimestamp()
    {
        return $this->container['timestamp'];
    }

    /**
     * Sets timestamp
     *
     * @param int $timestamp Numeric representation of the transaction's timestamp
     *
     * @return self
     */
    public function setTimestamp($timestamp)
    {
        if (is_null($timestamp)) {
            throw new \InvalidArgumentException('non-nullable timestamp cannot be null');
        }
        $this->container['timestamp'] = $timestamp;

        return $this;
    }

    /**
     * Gets tokenBalanceChanges
     *
     * @return \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashSolanaRITokenBalanceChangesInner[]
     */
    public function getTokenBalanceChanges()
    {
        return $this->container['tokenBalanceChanges'];
    }

    /**
     * Sets tokenBalanceChanges
     *
     * @param \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashSolanaRITokenBalanceChangesInner[] $tokenBalanceChanges Object Array representation of the transactions token (SPL) balance changes of each address and token
     *
     * @return self
     */
    public function setTokenBalanceChanges($tokenBalanceChanges)
    {
        if (is_null($tokenBalanceChanges)) {
            throw new \InvalidArgumentException('non-nullable tokenBalanceChanges cannot be null');
        }
        $this->container['tokenBalanceChanges'] = $tokenBalanceChanges;

        return $this;
    }

    /**
     * Gets tokenMovements
     *
     * @return \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashSolanaRITokenMovementsInner[]
     */
    public function getTokenMovements()
    {
        return $this->container['tokenMovements'];
    }

    /**
     * Sets tokenMovements
     *
     * @param \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashSolanaRITokenMovementsInner[] $tokenMovements Object Array representation of the transactions token movements
     *
     * @return self
     */
    public function setTokenMovements($tokenMovements)
    {
        if (is_null($tokenMovements)) {
            throw new \InvalidArgumentException('non-nullable tokenMovements cannot be null');
        }
        $this->container['tokenMovements'] = $tokenMovements;

        return $this;
    }

    /**
     * Gets minedInBlock
     *
     * @return \CryptoapisApiClient\Model\ListTransactionsByAddressSolanaRIMinedInBlock
     */
    public function getMinedInBlock()
    {
        return $this->container['minedInBlock'];
    }

    /**
     * Sets minedInBlock
     *
     * @param \CryptoapisApiClient\Model\ListTransactionsByAddressSolanaRIMinedInBlock $minedInBlock minedInBlock
     *
     * @return self
     */
    public function setMinedInBlock($minedInBlock)
    {
        if (is_null($minedInBlock)) {
            throw new \InvalidArgumentException('non-nullable minedInBlock cannot be null');
        }
        $this->container['minedInBlock'] = $minedInBlock;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


