<?php
/**
 * GetTransactionDetailsByTransactionHashUTXOsRI
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  CryptoapisApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CryptoAPIs
 *
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace CryptoapisApiClient\Model;

use \ArrayAccess;
use \CryptoapisApiClient\ObjectSerializer;

/**
 * GetTransactionDetailsByTransactionHashUTXOsRI Class Doc Comment
 *
 * @category Class
 * @package  CryptoapisApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetTransactionDetailsByTransactionHashUTXOsRI implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetTransactionDetailsByTransactionHashUTXOsRI';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'isConfirmed' => 'bool',
        'locktime' => 'int',
        'size' => 'int',
        'transactionID' => 'string',
        'version' => 'int',
        'fee' => '\CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRIFee',
        'hash' => 'string',
        'inputs' => '\CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRIInputsInner[]',
        'outputs' => '\CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRIOutputsInner[]',
        'positionInBlock' => 'int',
        'recipients' => '\CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRIRecipientsInner[]',
        'senders' => '\CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRISendersInner[]',
        'timestamp' => 'int',
        'minedInBlock' => '\CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRIMinedInBlock',
        'blockchainSpecific' => '\CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRIBSZ'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'isConfirmed' => null,
        'locktime' => 'int64',
        'size' => null,
        'transactionID' => null,
        'version' => null,
        'fee' => null,
        'hash' => null,
        'inputs' => null,
        'outputs' => null,
        'positionInBlock' => null,
        'recipients' => null,
        'senders' => null,
        'timestamp' => null,
        'minedInBlock' => null,
        'blockchainSpecific' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'isConfirmed' => false,
        'locktime' => false,
        'size' => false,
        'transactionID' => false,
        'version' => false,
        'fee' => false,
        'hash' => false,
        'inputs' => false,
        'outputs' => false,
        'positionInBlock' => false,
        'recipients' => false,
        'senders' => false,
        'timestamp' => false,
        'minedInBlock' => false,
        'blockchainSpecific' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'isConfirmed' => 'isConfirmed',
        'locktime' => 'locktime',
        'size' => 'size',
        'transactionID' => 'transactionID',
        'version' => 'version',
        'fee' => 'fee',
        'hash' => 'hash',
        'inputs' => 'inputs',
        'outputs' => 'outputs',
        'positionInBlock' => 'positionInBlock',
        'recipients' => 'recipients',
        'senders' => 'senders',
        'timestamp' => 'timestamp',
        'minedInBlock' => 'minedInBlock',
        'blockchainSpecific' => 'blockchainSpecific'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'isConfirmed' => 'setIsConfirmed',
        'locktime' => 'setLocktime',
        'size' => 'setSize',
        'transactionID' => 'setTransactionID',
        'version' => 'setVersion',
        'fee' => 'setFee',
        'hash' => 'setHash',
        'inputs' => 'setInputs',
        'outputs' => 'setOutputs',
        'positionInBlock' => 'setPositionInBlock',
        'recipients' => 'setRecipients',
        'senders' => 'setSenders',
        'timestamp' => 'setTimestamp',
        'minedInBlock' => 'setMinedInBlock',
        'blockchainSpecific' => 'setBlockchainSpecific'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'isConfirmed' => 'getIsConfirmed',
        'locktime' => 'getLocktime',
        'size' => 'getSize',
        'transactionID' => 'getTransactionID',
        'version' => 'getVersion',
        'fee' => 'getFee',
        'hash' => 'getHash',
        'inputs' => 'getInputs',
        'outputs' => 'getOutputs',
        'positionInBlock' => 'getPositionInBlock',
        'recipients' => 'getRecipients',
        'senders' => 'getSenders',
        'timestamp' => 'getTimestamp',
        'minedInBlock' => 'getMinedInBlock',
        'blockchainSpecific' => 'getBlockchainSpecific'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('isConfirmed', $data ?? [], null);
        $this->setIfExists('locktime', $data ?? [], null);
        $this->setIfExists('size', $data ?? [], null);
        $this->setIfExists('transactionID', $data ?? [], null);
        $this->setIfExists('version', $data ?? [], null);
        $this->setIfExists('fee', $data ?? [], null);
        $this->setIfExists('hash', $data ?? [], null);
        $this->setIfExists('inputs', $data ?? [], null);
        $this->setIfExists('outputs', $data ?? [], null);
        $this->setIfExists('positionInBlock', $data ?? [], null);
        $this->setIfExists('recipients', $data ?? [], null);
        $this->setIfExists('senders', $data ?? [], null);
        $this->setIfExists('timestamp', $data ?? [], null);
        $this->setIfExists('minedInBlock', $data ?? [], null);
        $this->setIfExists('blockchainSpecific', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['isConfirmed'] === null) {
            $invalidProperties[] = "'isConfirmed' can't be null";
        }
        if ($this->container['locktime'] === null) {
            $invalidProperties[] = "'locktime' can't be null";
        }
        if ($this->container['size'] === null) {
            $invalidProperties[] = "'size' can't be null";
        }
        if ($this->container['transactionID'] === null) {
            $invalidProperties[] = "'transactionID' can't be null";
        }
        if ($this->container['version'] === null) {
            $invalidProperties[] = "'version' can't be null";
        }
        if ($this->container['fee'] === null) {
            $invalidProperties[] = "'fee' can't be null";
        }
        if ($this->container['hash'] === null) {
            $invalidProperties[] = "'hash' can't be null";
        }
        if ($this->container['inputs'] === null) {
            $invalidProperties[] = "'inputs' can't be null";
        }
        if ($this->container['outputs'] === null) {
            $invalidProperties[] = "'outputs' can't be null";
        }
        if ($this->container['positionInBlock'] === null) {
            $invalidProperties[] = "'positionInBlock' can't be null";
        }
        if ($this->container['recipients'] === null) {
            $invalidProperties[] = "'recipients' can't be null";
        }
        if ($this->container['senders'] === null) {
            $invalidProperties[] = "'senders' can't be null";
        }
        if ($this->container['timestamp'] === null) {
            $invalidProperties[] = "'timestamp' can't be null";
        }
        if ($this->container['minedInBlock'] === null) {
            $invalidProperties[] = "'minedInBlock' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets isConfirmed
     *
     * @return bool
     */
    public function getIsConfirmed()
    {
        return $this->container['isConfirmed'];
    }

    /**
     * Sets isConfirmed
     *
     * @param bool $isConfirmed Boolean representation of if the transaction is mined
     *
     * @return self
     */
    public function setIsConfirmed($isConfirmed)
    {
        if (is_null($isConfirmed)) {
            throw new \InvalidArgumentException('non-nullable isConfirmed cannot be null');
        }
        $this->container['isConfirmed'] = $isConfirmed;

        return $this;
    }

    /**
     * Gets locktime
     *
     * @return int
     */
    public function getLocktime()
    {
        return $this->container['locktime'];
    }

    /**
     * Sets locktime
     *
     * @param int $locktime Numeric representation of the transaction locktime
     *
     * @return self
     */
    public function setLocktime($locktime)
    {
        if (is_null($locktime)) {
            throw new \InvalidArgumentException('non-nullable locktime cannot be null');
        }
        $this->container['locktime'] = $locktime;

        return $this;
    }

    /**
     * Gets size
     *
     * @return int
     */
    public function getSize()
    {
        return $this->container['size'];
    }

    /**
     * Sets size
     *
     * @param int $size Numeric representation of the transaction size
     *
     * @return self
     */
    public function setSize($size)
    {
        if (is_null($size)) {
            throw new \InvalidArgumentException('non-nullable size cannot be null');
        }
        $this->container['size'] = $size;

        return $this;
    }

    /**
     * Gets transactionID
     *
     * @return string
     */
    public function getTransactionID()
    {
        return $this->container['transactionID'];
    }

    /**
     * Sets transactionID
     *
     * @param string $transactionID String representation of the transaction identifier (txid)
     *
     * @return self
     */
    public function setTransactionID($transactionID)
    {
        if (is_null($transactionID)) {
            throw new \InvalidArgumentException('non-nullable transactionID cannot be null');
        }
        $this->container['transactionID'] = $transactionID;

        return $this;
    }

    /**
     * Gets version
     *
     * @return int
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param int $version Numeric representation of the transaction version
     *
     * @return self
     */
    public function setVersion($version)
    {
        if (is_null($version)) {
            throw new \InvalidArgumentException('non-nullable version cannot be null');
        }
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets fee
     *
     * @return \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRIFee
     */
    public function getFee()
    {
        return $this->container['fee'];
    }

    /**
     * Sets fee
     *
     * @param \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRIFee $fee fee
     *
     * @return self
     */
    public function setFee($fee)
    {
        if (is_null($fee)) {
            throw new \InvalidArgumentException('non-nullable fee cannot be null');
        }
        $this->container['fee'] = $fee;

        return $this;
    }

    /**
     * Gets hash
     *
     * @return string
     */
    public function getHash()
    {
        return $this->container['hash'];
    }

    /**
     * Sets hash
     *
     * @param string $hash String representation of the weight
     *
     * @return self
     */
    public function setHash($hash)
    {
        if (is_null($hash)) {
            throw new \InvalidArgumentException('non-nullable hash cannot be null');
        }
        $this->container['hash'] = $hash;

        return $this;
    }

    /**
     * Gets inputs
     *
     * @return \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRIInputsInner[]
     */
    public function getInputs()
    {
        return $this->container['inputs'];
    }

    /**
     * Sets inputs
     *
     * @param \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRIInputsInner[] $inputs Object Array representation of transaction inputs
     *
     * @return self
     */
    public function setInputs($inputs)
    {
        if (is_null($inputs)) {
            throw new \InvalidArgumentException('non-nullable inputs cannot be null');
        }
        $this->container['inputs'] = $inputs;

        return $this;
    }

    /**
     * Gets outputs
     *
     * @return \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRIOutputsInner[]
     */
    public function getOutputs()
    {
        return $this->container['outputs'];
    }

    /**
     * Sets outputs
     *
     * @param \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRIOutputsInner[] $outputs Object Array representation of transaction outputs
     *
     * @return self
     */
    public function setOutputs($outputs)
    {
        if (is_null($outputs)) {
            throw new \InvalidArgumentException('non-nullable outputs cannot be null');
        }
        $this->container['outputs'] = $outputs;

        return $this;
    }

    /**
     * Gets positionInBlock
     *
     * @return int
     */
    public function getPositionInBlock()
    {
        return $this->container['positionInBlock'];
    }

    /**
     * Sets positionInBlock
     *
     * @param int $positionInBlock Numeric representation of the transaction index
     *
     * @return self
     */
    public function setPositionInBlock($positionInBlock)
    {
        if (is_null($positionInBlock)) {
            throw new \InvalidArgumentException('non-nullable positionInBlock cannot be null');
        }
        $this->container['positionInBlock'] = $positionInBlock;

        return $this;
    }

    /**
     * Gets recipients
     *
     * @return \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRIRecipientsInner[]
     */
    public function getRecipients()
    {
        return $this->container['recipients'];
    }

    /**
     * Sets recipients
     *
     * @param \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRIRecipientsInner[] $recipients Object Array representation of transaction receivers
     *
     * @return self
     */
    public function setRecipients($recipients)
    {
        if (is_null($recipients)) {
            throw new \InvalidArgumentException('non-nullable recipients cannot be null');
        }
        $this->container['recipients'] = $recipients;

        return $this;
    }

    /**
     * Gets senders
     *
     * @return \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRISendersInner[]
     */
    public function getSenders()
    {
        return $this->container['senders'];
    }

    /**
     * Sets senders
     *
     * @param \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRISendersInner[] $senders Object Array representation of transaction senders
     *
     * @return self
     */
    public function setSenders($senders)
    {
        if (is_null($senders)) {
            throw new \InvalidArgumentException('non-nullable senders cannot be null');
        }
        $this->container['senders'] = $senders;

        return $this;
    }

    /**
     * Gets timestamp
     *
     * @return int
     */
    public function getTimestamp()
    {
        return $this->container['timestamp'];
    }

    /**
     * Sets timestamp
     *
     * @param int $timestamp Numeric representation of the timestamp in seconds since epoch
     *
     * @return self
     */
    public function setTimestamp($timestamp)
    {
        if (is_null($timestamp)) {
            throw new \InvalidArgumentException('non-nullable timestamp cannot be null');
        }
        $this->container['timestamp'] = $timestamp;

        return $this;
    }

    /**
     * Gets minedInBlock
     *
     * @return \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRIMinedInBlock
     */
    public function getMinedInBlock()
    {
        return $this->container['minedInBlock'];
    }

    /**
     * Sets minedInBlock
     *
     * @param \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRIMinedInBlock $minedInBlock minedInBlock
     *
     * @return self
     */
    public function setMinedInBlock($minedInBlock)
    {
        if (is_null($minedInBlock)) {
            throw new \InvalidArgumentException('non-nullable minedInBlock cannot be null');
        }
        $this->container['minedInBlock'] = $minedInBlock;

        return $this;
    }

    /**
     * Gets blockchainSpecific
     *
     * @return \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRIBSZ|null
     */
    public function getBlockchainSpecific()
    {
        return $this->container['blockchainSpecific'];
    }

    /**
     * Sets blockchainSpecific
     *
     * @param \CryptoapisApiClient\Model\GetTransactionDetailsByTransactionHashUTXOsRIBSZ|null $blockchainSpecific blockchainSpecific
     *
     * @return self
     */
    public function setBlockchainSpecific($blockchainSpecific)
    {
        if (is_null($blockchainSpecific)) {
            throw new \InvalidArgumentException('non-nullable blockchainSpecific cannot be null');
        }
        $this->container['blockchainSpecific'] = $blockchainSpecific;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


